#!/bin/sh

PROGNAME="$0"

usage() {
	cat <<EOF
NAME
    `basename $PROGNAME` - grep for numbers in text

SYNOPSIS
    `basename $PROGNAME` [options] [file] ...

DESCRIPTION
    grep for numbers in text using stdin or files.

OPTIONS
    -p pat	grep for 'pat' instead of numbers
    -s		Remove the sed stuff
    -D lvl	Debug level

EXAMPLE
    Grep for http://coord.info/GC51TNR:

	$ geo-text2numbers 
	If this event takes place we would be elated. If our favorite freighter
	sails again please phone us. it's even possible it would come this way.
	We would love to see her again.
	seven
	four
	eight
	one
	seven
	two

    Grep using pattern:

	$ geo-text2numbers  -p '<em>.' GC6KWN9.html
	<em>n
	<em>t
	<em>h
	<em>r
	<em>e
	<em>e
	<em>s
	<em>e
	<em>v
	<em>e
	<em>n

    Grep using pattern and remove the sed stuff:

	$ geo-text2numbers -p 'em>[^<]*</em' < GC8V3WN.html
	em>fi</em
	em>n</em
	em>d</em
	em>T</em
	em>He</em
	em>l</em
	em>o</em
	em>c</em
	em>a</em
	em>ti</em
	em>on</em
	$ geo-text2numbers -s -p 'em>[^<]*</em' < GC8V3WN.html
	findTHelocation

	$ geo-text2numbers -s -p '<em>.' < GC6KWN9.html
	nthreeseventWo6eight0eigHt1Two6556nine2
EOF

	exit 1
}

#
#       Report an error and exit
#
error() {
	echo "`basename $PROGNAME`: $1" >&2
	exit 1
}

debug() {
	if [ $DEBUG -ge $1 ]; then
	    echo "`basename $PROGNAME`: $2" >&2
	fi
}

#
#       Process the options
#
DEBUG=0
PAT=
SED=0
while getopts "p:sD:h?" opt
do
	case $opt in
	p)	PAT="$OPTARG";;
	s)	SED=1;;
	D)	DEBUG="$OPTARG";;
	h|\?)	usage;;
	esac
done
shift `expr $OPTIND - 1`

FILES=$*

#
#	Main Program
#
if [ "$PAT" = "" ]; then
    cat $FILES | tr -d -c '[a-zA-Z]' |
    tr A-Z a-z |
    egrep -o --color \
    'north|east|south|west|zero|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eightteen|nineteen|twenty|thirty|forty|fifty|sixty|seventy|eighty|ninety|hundred|thousand|million|nought|nil'
else
    if [ $SED = 1 ]; then
	initial=$( echo "$PAT" |
	    sed -e 's/\..*//' -e 's/\[.*//' )
	final=$( echo "$PAT" |
	    sed -e 's/^.*\.//' -e 's/^.*\*//' -e 's/^.*\]//' )
	cat $FILES |
	    grep -o "$PAT" |
	    sed -e "s/$initial//" -e "s@$final@@" |
	    tr -d '\012'
	echo
    else
	cat $FILES | grep -o "$PAT"
    fi
fi
